name: down-foreign

on:
  watch:
    types: [started]
    
env:
  FILE_URL: https://master.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/MIUI-WEEKLY-RELEASES/20.8.27/xiaomi.eu_multi_MIMAX3_20.8.27_v12-10.zip
  FILE_NAME: xiaomi.eu_multi_MIMAX3_20.8.27_v12-10.zip
    
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment 
      run: sudo apt install wget

    - name: Download File
      run: |
        wget -O $FILE_NAME $FILE_URL
        
    - name: Upload File to WeTransfer
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet $FILE_NAME
