name: down-foreign

on:
  watch:
    types: [started]
    
env:
  FILE_URL: https://master.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/MIUI-WEEKLY-RELEASES/20.8.27/xiaomi.eu_multi_MIMAX3_20.8.27_v12-10.zip
  FILE_NAME: SGSI-build-tool.tar
  GITHUB_RELEASE: true
  URL_DOWN: false
    
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment 
      run: sudo apt install wget

    - name: Download File
      if: env.URL_DOWN == 'true'
      run: |
        wget -O $FILE_NAME $FILE_URL
      
    - name: Download Github Release
      if: env.GITHUB_RELEASE == 'true'
      uses: robinraju/release-downloader@v1
      with:
        repository: "xiaoxindada/SGSI-build-tool"
        latest: true
        fileName: "SGSI-build-tool.tar"

    - name: Upload File to WeTransfer
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet $FILE_NAME
